# Generated by Django 4.0.3 on 2022-05-19 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='')),
                ('thumbnail_img', models.ImageField(null=True, upload_to='images/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('singer', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuteeVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutee_video', models.FileField(upload_to='')),
                ('tutor_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danmer.tutorvideopost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_per_part', models.JSONField(default=dict)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danmer.tuteevideopost')),
            ],
        ),
    ]
