# Generated by Django 4.0.3 on 2022-06-04 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_url', models.FileField(upload_to='tutor_videos/')),
                ('thumbnail_url', models.ImageField(null=True, upload_to='images/')),
                ('song_artist', models.CharField(max_length=100)),
                ('coordinate_url', models.FileField(null=True, upload_to='tutor_vibe/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuteeVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutee_video', models.FileField(upload_to='tutee_videos/')),
                ('feedback_result', models.JSONField(default=dict)),
                ('tutor_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danmer.tutorvideopost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
