# Generated by Django 4.0.3 on 2022-05-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danmer', '0002_remove_tutorvideopost_video_url_tutorvideopost_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuteevideopost',
            old_name='tutee_video_url',
            new_name='tutee_video',
        ),
    ]
