# Generated by Django 4.0.3 on 2022-06-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmer', '0002_alter_tuteevideopost_feedback_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorvideopost',
            name='coordinate_url',
            field=models.URLField(null=True),
        ),
    ]
